version: 0  # all version values must be the same
include:    # included files update top level config, they must exist
  - logging.yaml
  - rpsl.yaml
# vim:set ft=yaml ai et ts=2 sts=2 sw=2 cc=80:EOF #
